package dvdrental;
// Generated Mar 30, 2017 10:35:35 PM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Inventory generated by hbm2java
 */
public class Inventory  implements java.io.Serializable {


     private int inventoryId;
     private Film film;
     private Store store;
     private Date lastUpdate;
     private Set<Rental> rentals = new HashSet<Rental>(0);

    public Inventory() {
    }

	
    public Inventory(int inventoryId, Film film, Store store, Date lastUpdate) {
        this.inventoryId = inventoryId;
        this.film = film;
        this.store = store;
        this.lastUpdate = lastUpdate;
    }
    public Inventory(int inventoryId, Film film, Store store, Date lastUpdate, Set<Rental> rentals) {
       this.inventoryId = inventoryId;
       this.film = film;
       this.store = store;
       this.lastUpdate = lastUpdate;
       this.rentals = rentals;
    }
   
    public int getInventoryId() {
        return this.inventoryId;
    }
    
    public void setInventoryId(int inventoryId) {
        this.inventoryId = inventoryId;
    }
    public Film getFilm() {
        return this.film;
    }
    
    public void setFilm(Film film) {
        this.film = film;
    }
    public Store getStore() {
        return this.store;
    }
    
    public void setStore(Store store) {
        this.store = store;
    }
    public Date getLastUpdate() {
        return this.lastUpdate;
    }
    
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }
    public Set<Rental> getRentals() {
        return this.rentals;
    }
    
    public void setRentals(Set<Rental> rentals) {
        this.rentals = rentals;
    }




}


